config/routes.rb
Rails.application.routes.draw do

  

  resources :m4rotations do
  	resources :m4comments
  end

  resource :session

  resources :users

  root "landing#index"

  get"/home" => "home#index"

  get "/signup" => "users#new"

  resources :rotations do
  	  resources :comments 	  	
  end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :rotation

  validates :name, presence: true
  validates :body, presence: true
  validates :rating, allow_blank: true, numericality: true , :inclusion => 1..10

  
end

app/models/m4comment.rb
class M4comment < ActiveRecord::Base
  belongs_to :m4rotation

  validates :name, presence: true
  validates :body, presence: true
  validates :rating, allow_blank: true, numericality: true, :inclusion => 1..10

end

app/models/m4rotation.rb
class M4rotation < ActiveRecord::Base
	has_many :m4comments, dependent: :destroy 
end

app/models/rotation.rb
class Rotation < ActiveRecord::Base
	has_many :comments, dependent: :destroy 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true,
  					format: /\A\S+@uic.edu\z/,
  					uniqueness: {case_sensitive: false}

	def self.authenticate(email, password)
		user = User.find_by(email: email)
		user && user.authenticate(password)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	private
	  def require_signin
	  	unless current_user
	  		session[:intended_url] = request.url
	  		redirect_to new_session_url, alert: "Please sign in first!"	  	
	  	end
	  end

	def current_user
	 	@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	helper_method :current_user

	def require_admin
		unless current_user_admin?
			redirect_to root_url, alert: "Unauthorized access!"
		end
	end

	def current_user_admin?
		current_user && current_user.admin?
	end

	helper_method :current_user_admin?


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :require_signin
	before_action :require_admin, only: [:destroy]



	def index
		@rotation = Rotation.find(params[:rotation_id])
		@comments = @rotation.comments
	end

	def new
		@rotation = Rotation.find(params[:rotation_id])
		@comment = @rotation.comments.new
	end

	def create
		@rotation = Rotation.find(params[:rotation_id])
		@comment = @rotation.comments.new(comment_params)
		if @comment.save
			redirect_to rotation_comments_path(@rotation),
					notice: "Thanks for your comment!"
		else
			render :new
		end
	end

	def show
		@comment = Comment.find(params[:id])

		@rotation = Rotation.find(params[:rotation_id])
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to rotation_comments_path
	end







	private

	def comment_params
		params.require(:comment).permit(:name, :body, :created_at, :rating)
	end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

	layout false, only: :index 

	def index
	end
end

app/controllers/m4comments_controller.rb
class M4commentsController < ApplicationController
	before_action :require_signin
	before_action :require_admin, only: [:destroy]

	def index
		@m4rotation = M4rotation.find(params[:m4rotation_id])
		@m4comments = @m4rotation.m4comments
	end

	def show
		@m4comment = M4comment.find(params[:id])
		@m4rotation = M4rotation.find(params[:m4rotation_id])
	end

	def new
		@m4rotation = M4rotation.find(params[:m4rotation_id])
		@m4comment = @m4rotation.m4comments.new
	end

	def create
		@m4rotation = M4rotation.find(params[:m4rotation_id])
		@m4comment = @m4rotation.m4comments.new(m4comment_params)
			if @m4comment.save
				redirect_to m4rotation_m4comments_path(@m4rotation),
						notice: "Thanks for your comment!"
			else
				render :new
			end
	end

	def destroy
		@m4comment = M4comment.find(params[:id])
		@m4comment.destroy
		redirect_to m4rotation_m4comments_path 
		
	end
end


private

	def m4comment_params
		params.require(:m4comment).permit(:name, :body, :created_at, :rating)
		
	end

app/controllers/m4rotations_controller.rb
class M4rotationsController < ApplicationController
	before_action :require_signin, only: [:show]
	before_action :require_admin, except: [:index, :show]

	def index
		@m4rotations = M4rotation.all 

	end

	def show
		@m4rotation = M4rotation.find(params[:id])
	end

	def new
		@m4rotation = M4rotation.new
	end

	def create
		@m4rotation = M4rotation.create(m4rotation_params)
		redirect_to m4rotations_path	
	end

	def edit

		@m4rotation = M4rotation.find(params[:id])
		
	end

	def update
		@m4rotation = M4rotation.find(params[:id])
		@m4rotation.update(m4rotation_params)
		redirect_to m4rotation_path(@m4rotation)
	end

	def destroy
		@m4rotation = M4rotation.find(params[:id])
		@m4rotation.destroy 
		redirect_to m4rotations_path
	end

end

private

def	m4rotation_params 
	params[:m4rotation].permit(:name, :duration, :hours, :location)
end

app/controllers/rotations_controller.rb
class RotationsController < ApplicationController
	before_action :require_signin, only: [:show]
	before_action :require_admin, except: [:index, :show]

		def index
			@rotations = Rotation.all
		end

		def show
			@rotation = Rotation.find(params[:id])

		end

		def edit
			@rotation = Rotation.find(params[:id])
		end
	
		def update
			@rotation = Rotation.find(params[:id])
			@rotation.update(rotation_params)
			redirect_to @rotation
		end

		def new
			@rotation = Rotation.new

		end

		def create
			@rotation = Rotation.create(rotation_params)
			redirect_to rotations_path
		end

		def destroy
			@rotation = Rotation.find(params[:id])
			@rotation.destroy
			redirect_to rotations_path
			
		end
end


private

def	rotation_params 
	params[:rotation].permit(:name, :duration, :hours, :location)
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		if user = User.authenticate(params[:email], params[:password])
			session[:user_id] = user.id
			flash[:notice] = "Welcome back, #{user.name}!"
			redirect_to(session[:intended_url] || rotations_path)
			session[:intended_url] = nil
		else
			flash.now[:alert] = "Invalid email/password combination!"
			render :new
		end

	end

	def destroy
		session[:user_id] = nil
		redirect_to rotations_path, notice: "You're now signed out!"
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_signin, except: [:new, :create]
	before_action :require_admin, only: [:destroy]

		def index
			@users = User.all	
		end

		def new
			@user = User.new	
		end

		def create
			@user = User.new(user_params)
			if @user.save
				session[:user_id] = @user.id
				redirect_to(session[:intended_url] || rotations_path, notice: "Welcome, #{@user.name}. Thanks for signing up!")
				session[:intended_url] = nil
			else
				render :new
			end
		end

		def destroy
			@user = User.find(params[:id])
			@user.destroy
			redirect_to users_path
		end






	private

	def user_params
		params.require(:user).
			permit(:name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

# def markdown(text)
# 	#  markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, 
# 	# 	no_intra_emphasis: true, 
# 	#     fenced_code_blocks: true,   
# 	#     disable_indented_code_blocks: true)
# 	# return markdown.render(text).html_safe

# end

  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true, 
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true, 
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end



end

app/helpers/comments_helper.rb
module CommentsHelper

	def format_rating(rating)
		if rating.blank?
		else
			"Rating: #{rating} / 10 "
		end
	end

	def format_date(date)
		date.strftime('%D')		
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/m4comments_helper.rb
module M4commentsHelper
end

app/helpers/m4rotations_helper.rb
module M4rotationsHelper
end

app/helpers/rotations_helper.rb
module RotationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb

<div class = "container" id = "comments_title">
	<div class = "col-md-4" id = "vertical">
		<%=link_to("< Back to Rotation", rotation_path(@rotation), :class => 'btn btn-primary btn-large')%>
	</div>

	<div class = "col-md-4">
		<h1><%=@rotation.name %> Comments</h1>
	</div>
	<div class = "col-md-4" id = "vertical">
		<%=link_to("+ Add New Comment", new_rotation_comment_path, :class => 'btn btn-primary btn-large')%> 
	</div>
</div>
	
<div class = "panel panel-default" id="comment_panel">
	
	<% @comments.order("created_at desc").each do |comment| %>
		

			<div class = "panel-heading">

				<h2><%= comment.name %></h2>   	<p>Posted: <%= format_date(comment.created_at)%></p>
				<p> <%=format_rating(comment.rating)%> </p>
			</div>
	
	
	 <%= markdown(truncate((comment.body), length: 1000, separator: ' '))%> 
	 

		<% if comment.body.size > 1000 %> 
			 <div class = "more">
			 <%=link_to('Read More...', rotation_comment_path(@rotation, comment)) %>
			</div>
		<% end %>


		<% if current_user_admin? %>
			<%=link_to "Delete", rotation_comment_path(@rotation, comment), method: :delete, data: {confirm: 'Are you sure?'}%>
		<% end %> <br><br><br><br><br>
		
	<% end %> </ul> 
</div>





<div class = "container">
	<%=link_to("+ Add New Comment", new_rotation_comment_path, :class => 'btn btn-primary btn-large', :id => 'big_btn')%>
</div>







app/views/comments/new.html.erb
<div class = 'container'>
  <div class = "col-md-4">
     <%= link_to("< Back to #{@rotation.name} Comments", rotation_comments_path(@rotation), :class => 'btn btn-primary btn-large', :id => 'vertical')%> 
      </p>
  </div>
  <div class = "col-md-4">
    <h1> Add Comment for <%= link_to(@rotation.name, @rotation)%> </h1>
  </div>
  <div class = "col-md-4">

  </div>
</div>

      <%= render "shared/errors", object: @comment %>

      <%= render "shared/commentform", object1: @rotation, object2: @comment %>

  </div>
</div>



app/views/comments/show.html.erb
<div class = "container" id="comment_title">
	<h1><%= @comment.name%>:</h1> <br>
</div>

<div class = "container1">
	<%= markdown(@comment.body) %>
	<br><br><br>
</div>

<div class = "container">
<%=link_to("Back to #{@rotation.name} Comments", rotation_comments_path(@rotation), :class => 'btn btn-primary btn-larg')%>

</div>

app/views/m4comments/index.html.erb
<div class = "container" id = "comments_title">
	<div class = "col-md-4" id = "vertical">
		<%=link_to("< Back to Rotation", m4rotation_path(@m4rotation), :class => 'btn btn-primary btn-large')%>
	</div>

	<div class = "col-md-4">
		<h1><%=@m4rotation.name %> Comments</h1>
	</div>
	<div class = "col-md-4" id = "vertical">
		<%=link_to("+ Add New Comment", new_m4rotation_m4comment_path, :class => 'btn btn-primary btn-large')%> 
	</div>
</div>
	
<div class = "panel panel-default" id="comment_panel">
	
	<% @m4comments.order("created_at desc").each do |comment| %>
		

			<div class = "panel-heading">

				<h2><%= comment.name %></h2>   	<p>Posted: <%= format_date(comment.created_at)%></p>
				<p> <%=format_rating(comment.rating)%> </p>
			</div>
			
			<%= markdown(truncate((comment.body), length: 1000, separator: ' '))%>


		 <% if comment.body.size > 1000 %>
		 	<div class = "more"><%=link_to('Read More...', m4rotation_m4comment_path(@m4rotation, comment)) %></div>
		 <% end %>

			<% if current_user_admin? %>
				<%=link_to "Delete", m4rotation_m4comment_path(@m4rotation, comment), method: :delete, data: {confirm: 'Are you sure?'}%>
			<% end %> <br><br><br><br><br>
		
	<% end %> </ul> 
</div>





<div class = "container">
	<%=link_to("+ Add New Comment", new_m4rotation_m4comment_path, :class => 'btn btn-primary btn-large', :id => 'big_btn')%>
</div>

app/views/m4comments/new.html.erb
<div class = 'container'>
  <div class = "col-md-4">
     <%= link_to("< Back to #{@m4rotation.name} Comments", m4rotation_m4comments_path(@m4rotation), :class => 'btn btn-primary btn-large', :id => 'vertical')%> 
      </p>
  </div>
  <div class = "col-md-4">
    <h1> Add Comment for <%= link_to(@m4rotation.name, @m4rotation)%> </h1>
  </div>
  <div class = "col-md-4">

  </div>
</div>

      <%= render "shared/errors", object: @m4comment %>

      <%= render "shared/commentform", object1: @m4rotation, object2: @m4comment %>
</div>

app/views/m4comments/show.html.erb
<div class = "container" id="comment_title">
	<h1><%= @m4comment.name%>:</h1> <br>
</div>

<div class = "container1">

		<%= markdown(@m4comment.body)%>
	<br><br><br>
</div>

<div class = "container">
<%=link_to("Back to #{@m4rotation.name} Comments", m4rotation_m4comments_path(@m4rotation), :class => 'btn btn-primary btn-larg')%>

</div>

app/views/m4rotations/edit.html.erb
<div class = "container" >

	<%= render "shared/form", object: @m4rotation %>

</div>

app/views/m4rotations/index.html.erb

<div class="container">
	<h1> M4 Rotations </h1>
	<div>
		<div class="list-group">
			<% @m4rotations.each do |m4rotation| %>
			<%= link_to(m4rotation.name, m4rotation_path(m4rotation), :class => "list-group-item")%>
			<%end%>
		<ul>
	</div>
	<% if current_user_admin? %>
		<%= link_to('Add Rotation', new_m4rotation_path) %>
	<% end %>
</div>

app/views/m4rotations/new.html.erb
<div class = "container">

	<%=link_to("Back to Rotations", m4rotations_path) %>

	<%= render "shared/form", object: @m4rotation %>

</div>

app/views/m4rotations/show.html.erb
	<div class = "container">
			<div>
				<%= link_to("< Back to List", m4rotations_path, :class => 'btn btn-large btn-primary', :id => "back")%> 	
			</div>
			<div>
				<h1><%= @m4rotation.name %></h1>
			</div>
	</div>
	<div class = "container">
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title"> Duration:</h3>
		  </div>
		  <div class="panel-body">
		    <%=@m4rotation.duration %>
		  </div>
		</div>

		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title"> Estimated hours of work per week:</h3>
		  </div>
		  <div class="panel-body">
		    <%=@m4rotation.hours %>
		  </div>
		</div>
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title"> Location:</h3>
		  </div>
		  <div class="panel-body">
		    <%=@m4rotation.location%>
		  </div>
		</div>
	</div>


	<div class = "container">
		<%= link_to("View Student Comments >", m4rotation_m4comments_path(@m4rotation), :class => 'btn btn-primary btn-large', :id => 'comments') %> <br>
		
		<% if current_user_admin? %>	
			<%= link_to("Edit", edit_m4rotation_path(@m4rotation)) %> <br>
			<%= link_to("Delete", m4rotation_path(@m4rotation), method: :delete, data: {confirm: 'Are you sure?' }) %>
		<% end %>
	</div>

app/views/rotations/edit.html.erb


<%= form_for([@rotation]) do |f| %>
	<div class = "container">	
		<p>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</p>

		<p>
			<%= f.label :duration %>
			<%= f.text_field :duration %>
		</p>

		<p>
			<%= f.label :hours %>
			<%= f.text_field :hours %>
		</p>

		<p>
			<%= f.label :location %>
			<%= f.text_field :location %>
		</p>

		<%= f.submit %>
	</div>
<% end %>

app/views/rotations/index.html.erb

<div class="container">
	<h1> M3 Rotations </h1>
	<div>
		<div class="list-group">
			<% @rotations.each do |rotation| %>
			<%= link_to(rotation.name, rotation_path(rotation), :class => "list-group-item")%>
			<%end%>
		<ul>
	</div>
	<% if current_user_admin? %>
		<%= link_to('Add Rotation', new_rotation_path) %>
	<% end %>
</div>

app/views/rotations/new.html.erb
<%= form_for([@rotation]) do |f| %>

	<div class = "container">	
		<p>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</p>

		<p>
			<%= f.label :duration %>
			<%= f.text_field :duration %>
		</p>

		<p>
			<%= f.label :hours %>
			<%= f.text_field :hours %>
		</p>

		<p>
			<%= f.label :location %>
			<%= f.text_field :location %>
		</p>

		<%= f.submit %>
	</div>

<% end %>

app/views/rotations/show.html.erb

	<div class = "container">
			<div>
				<%= link_to("< Back to List", rotations_path, :class => 'btn btn-large btn-primary', :id => "back")%> 	
			</div>
			<div>
				<h1><%= @rotation.name %></h1>
			</div>
	</div>
	<div class = "container">
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title"> Duration:</h3>
		  </div>
		  <div class="panel-body">
		    <%=@rotation.duration %>
		  </div>
		</div>

		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title"> Estimated hours of work per week:</h3>
		  </div>
		  <div class="panel-body">
		    <%=@rotation.hours %>
		  </div>
		</div>
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title"> Location:</h3>
		  </div>
		  <div class="panel-body">
		    <%=@rotation.location%>
		  </div>
		</div>
	</div>


	<div class = "container">
		<%= link_to("View Student Comments >", rotation_comments_path(@rotation), :class => 'btn btn-primary btn-large', :id => 'comments') %> <br>
		<% if current_user_admin? %>	
			<%= link_to("Edit", edit_rotation_path(@rotation)) %> <br>
			<%= link_to("Delete", rotation_path(@rotation), method: :delete, data: {confirm: 'Are you sure?' }) %>
		<% end %>
	</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<%= render "shared/errors", object: @user %>
	<fieldset>
		<div class = "container">
			<div class ="col-md-4" id="sign_in">

					<h5> Due to current research being run on rotationsrx we are not taking any new sign ups from UICOMP M3's for the time being</h5>
					<h6> Please get in touch with Victor at rotationsrx@gmail.com if you have any questions!</h6>


				<!-- <div class = "required">

					<%= f.text_field :name, size: 40, autofocus: true, placeholder: 'Name' %>
				</div>

				<div class = "required">
					<%= f.email_field :email, size: 40, placeholder: 'UIC student email' %>
				</div>

				<div class = "required">
					<%= f.password_field :password, size: 40, placeholder: 'Password' %>
				</div>

				<div class = "required">
					<%= f.password_field :password_confirmation, size: 40, placeholder: 'Confirm Password' %>
				</div>

		
				<p>
					<%= f.submit "Create Account", :class => 'btn btn-primary btn-large' %>
				</p> -->
			</div>
		</div>
	</fieldset>
<% end %>

app/views/users/edit.html.erb
<header id = "content-header">
	<h1> Edit Account </h1>
</header>

<%= render 'form' %>

app/views/users/index.html.erb
<ul>
	<% @users.each do |user| %>
		<li> <h4><%= user.name %></h4> <b><%= user.email %></b> | <%= "#{user.created_at}".to_time(:local) %> | Admin: <%= user.admin %> | <%= link_to 'Delete Account', user,
							method: :delete,
							data: {confirm: 'Are you sure?'} %></li>

	<% end %>
</ul>

app/views/users/new.html.erb
<header class = "container" id = "content-header">
	<h1> Sign Up </h1>
</header>

<%= render "form" %>