config/routes.rb
Rails.application.routes.draw do

  

  resources :m4rotations do
  	resources :m4comments
  end

  resource :session

  resources :users

  root "landing#index"

  get"/home" => "home#index"

  get "/signup" => "users#new"

  resources :rotations do
  	  resources :comments 	  	
  end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :rotation

  validates :name, presence: true
  validates :body, presence: true
  validates :rating, allow_blank: true, numericality: true , :inclusion => 1..10

  
end

app/models/m4comment.rb
class M4comment < ActiveRecord::Base
  belongs_to :m4rotation

  validates :name, presence: true
  validates :body, presence: true
  validates :rating, allow_blank: true, numericality: true, :inclusion => 1..10

end

app/models/m4rotation.rb
class M4rotation < ActiveRecord::Base
	has_many :m4comments, dependent: :destroy 
end

app/models/rotation.rb
class Rotation < ActiveRecord::Base
	has_many :comments, dependent: :destroy 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true,
  					format: /\A\S+@uic.edu\z/,
  					uniqueness: {case_sensitive: false}

	def self.authenticate(email, password)
		user = User.find_by(email: email)
		user && user.authenticate(password)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :require_signin
	before_action :require_admin, only: [:destroy]



	def index
		@rotation = Rotation.find(params[:rotation_id])
		@comments = @rotation.comments
	end

	def new
		@rotation = Rotation.find(params[:rotation_id])
		@comment = @rotation.comments.new
	end

	def create
		@rotation = Rotation.find(params[:rotation_id])
		@comment = @rotation.comments.new(comment_params)
		if @comment.save
			redirect_to rotation_comments_path(@rotation),
					notice: "Thanks for your comment!"
		else
			render :new
		end
	end

	def show
		@comment = Comment.find(params[:id])

		@rotation = Rotation.find(params[:rotation_id])
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to rotation_comments_path
	end







	private

	def comment_params
		params.require(:comment).permit(:name, :body, :created_at, :rating)
	end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

	layout false, only: :index 

	def index
	end
end

app/controllers/rotations_controller.rb
class RotationsController < ApplicationController
	before_action :require_signin, only: [:show]
	before_action :require_admin, except: [:index, :show]

		def index
			@rotations = Rotation.all
		end

		def show
			@rotation = Rotation.find(params[:id])

		end

		def edit
			@rotation = Rotation.find(params[:id])
		end
	
		def update
			@rotation = Rotation.find(params[:id])
			@rotation.update(rotation_params)
			redirect_to @rotation
		end

		def new
			@rotation = Rotation.new

		end

		def create
			@rotation = Rotation.create(rotation_params)
			redirect_to rotations_path
		end

		def destroy
			@rotation = Rotation.find(params[:id])
			@rotation.destroy
			redirect_to rotations_path
			
		end
end


private

def	rotation_params 
	params[:rotation].permit(:name, :duration, :hours, :location)
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		if user = User.authenticate(params[:email], params[:password])
			session[:user_id] = user.id
			flash[:notice] = "Welcome back, #{user.name}!"
			redirect_to(session[:intended_url] || rotations_path)
			session[:intended_url] = nil
		else
			flash.now[:alert] = "Invalid email/password combination!"
			render :new
		end

	end

	def destroy
		session[:user_id] = nil
		redirect_to rotations_path, notice: "You're now signed out!"
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_signin, except: [:new, :create]
	before_action :require_admin, only: [:destroy]

		def index
			@users = User.all	
		end

		def new
			@user = User.new	
		end

		def create
			@user = User.new(user_params)
			if @user.save
				session[:user_id] = @user.id
				redirect_to(session[:intended_url] || rotations_path, notice: "Welcome, #{@user.name}. Thanks for signing up!")
				session[:intended_url] = nil
			else
				render :new
			end
		end

		def destroy
			@user = User.find(params[:id])
			@user.destroy
			redirect_to users_path
		end






	private

	def user_params
		params.require(:user).
			permit(:name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

# def markdown(text)
# 	#  markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, 
# 	# 	no_intra_emphasis: true, 
# 	#     fenced_code_blocks: true,   
# 	#     disable_indented_code_blocks: true)
# 	# return markdown.render(text).html_safe

# end

  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true, 
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true, 
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end



end

app/helpers/comments_helper.rb
module CommentsHelper

	def format_rating(rating)
		if rating.blank?
		else
			"Rating: #{rating} / 10 "
		end
	end

	def format_date(date)
		date.strftime('%D')		
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/m4comments_helper.rb
module M4commentsHelper
end

app/helpers/m4rotations_helper.rb
module M4rotationsHelper
end

app/helpers/rotations_helper.rb
module RotationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class = "alert alert-success"role="alert"><%= content_tag(:p, value, :class => "flash #{key}") %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>

<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
    <p> RotationsRx </p>
  </div>
</nav>

</footer>

app/views/layouts/_header.html.erb
<header id = "page-header">
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
      <a class="navbar-brand" href="/">RotationsRx</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <% if current_user_admin? %>
      	   <li><%= link_to "Users", users_path %></li>
        <% end %> 
        <li><%= link_to "M3 Rotations", rotations_path %></li>  
        <li><%= link_to "M4 Rotations", m4rotations_path %></li>

      <% if current_user %>

        <p id = "name" class = "navbar-text"> <%= current_user.name %> </p>
        <li><%= link_to 'Sign Out', session_path, method: :delete %> </li>
      <% else %>

        <li><%= link_to "Sign In", new_session_path %></li>   
        <li><%= link_to "Sign Up", signup_path, class: 'button' %></li>

      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


</header>




app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rotationsrx</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


<link type="text/css" rel="stylesheet" href="../../css/RotationsRx_attending_template.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> 
</script>

</head>

<body>

<%= render "layouts/header" %>

<%= render "layouts/flashes" %>

<%= yield %>

<%= render "layouts/footer" %>

</body>
</html>

app/views/shared/_commentform.html.erb
<div class = "container">
    <%= form_for([object1, object2]) do |f| %>

      <div class = "require">
        <p>
          <%= f.label "Comment Title (*required):" %><br/>
          <%= f.text_field :name, size: 40, autofocus: true, placeholder: "Short description/title for your comment" %>
        </p>
      </div>
      <p>
        <%= f.label "Comment (*required):" %><br/>
        <%= f.text_area :body, cols: "120", rows: "10", autofocus: true, placeholder: "Write comment here. Feel free to write whatever you would like. Common useful comments include: Where/when to show up on day one, how to study for the shelf, differences in teaching styles, which parts of the rotation are useful to get studying done, any unique aspects of the rotation, anything else you wish YOU had known when starting!" %>
      </p>
      <p>
        <%= f.label "#{object1.name} Rating: (optional)" %><br/>
        <%= f.select :rating, 1..10, autofocus: true, prompt: "Pick one" %>
      </p>
      
           <%= f.submit '+ Post Comment', :class => 'btn btn-primary btn-large', :id => 'big_btn' %>

    <% end %>	
  </div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<div class = "alert alert-danger" role = "alert"><section id="errors">
  <header>
    <h2>
      Oops! Could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </ul>
</section></div>
<% end %>

app/views/shared/_form.html.erb
<%= form_for ([object]) do |f| %>

	<div class = "container">	
		<p>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</p>

		<p>
			<%= f.label :duration %>
			<%= f.text_field :duration %>
		</p>

		<p>
			<%= f.label :hours %>
			<%= f.text_field :hours %>
		</p>

		<p>
			<%= f.label :location %>
			<%= f.text_field :location %>
		</p>

		<%= f.submit %>
	</div>


<% end %>